const fs = require("fs");
// fs.mkdirSync("thapa");
// fs.writeFileSync("thapa/bio.txt", "hello");
// fs.appendFileSync("thapa/bio.txt", "shubham");
// fs.readFileSync("thapa/bio.txt", "utf8");
// fs.renameSync("thapa/bio.txt", "thapa/mybio.txt");
// fs.unlinkSync("thapa/mybio.txt");
// fs.rmdirSync("thapa");
// fs.unlinkSync("bio.txt");
// console.log("hello");
